/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-09 17:08:39 UTC)
 * on 2014-07-20 at 04:01:25 UTC 
 * Modify at your own risk.
 */

package com.otto.serviceendpoint.model;

/**
 * Model definition for Service.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the serviceendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Service extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime end;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> messages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long routeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String routeName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long securityCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime start;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> track;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getEnd() {
    return end;
  }

  /**
   * @param end end or {@code null} for none
   */
  public Service setEnd(com.google.api.client.util.DateTime end) {
    this.end = end;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Service setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getMessages() {
    return messages;
  }

  /**
   * @param messages messages or {@code null} for none
   */
  public Service setMessages(java.util.List<java.lang.String> messages) {
    this.messages = messages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getRouteId() {
    return routeId;
  }

  /**
   * @param routeId routeId or {@code null} for none
   */
  public Service setRouteId(java.lang.Long routeId) {
    this.routeId = routeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRouteName() {
    return routeName;
  }

  /**
   * @param routeName routeName or {@code null} for none
   */
  public Service setRouteName(java.lang.String routeName) {
    this.routeName = routeName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSecurityCode() {
    return securityCode;
  }

  /**
   * @param securityCode securityCode or {@code null} for none
   */
  public Service setSecurityCode(java.lang.Long securityCode) {
    this.securityCode = securityCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getStart() {
    return start;
  }

  /**
   * @param start start or {@code null} for none
   */
  public Service setStart(com.google.api.client.util.DateTime start) {
    this.start = start;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTrack() {
    return track;
  }

  /**
   * @param track track or {@code null} for none
   */
  public Service setTrack(java.util.List<java.lang.String> track) {
    this.track = track;
    return this;
  }

  @Override
  public Service set(String fieldName, Object value) {
    return (Service) super.set(fieldName, value);
  }

  @Override
  public Service clone() {
    return (Service) super.clone();
  }

}
